Models/project/app1/urls.py
from app1 import views
from django.urls import path


app_name = 'app1'
urlpatterns = [

    path('models/' , views.users , name = 'users'),
    path('other/' , views.other , name = 'other') ,
    path('relative/' , views.relative , name = 'relative'),
    path('user_login/' , views.user_login , name = 'user_login'),


]

Models/project/project/urls.py
from django.contrib import admin
from app1 import views
from django.urls import path,include

urlpatterns = [
    path('' , views.index , name = 'index'),
    path('app1/',include('app1.urls')),
    path('logout/' , views.user_logout , name = 'logout'),
    path('special/' , views.special , name = 'special'),
    path('admin/', admin.site.urls),
]

Models/project/app1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User , on_delete=models.CASCADE)

    portfolio_link = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to= 'profile_pics' , blank=True)


    def __str__(self):
        return self.user.username

Models/project/app1/forms.py
from django import forms
from django.contrib.auth.models import User
from app1.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username' , 'email' , 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_link'  , 'profile_pic')

Models/project/app1/views.py
from django.shortcuts import render
from app1.forms import UserForm , UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth import authenticate , login , logout
# Create your views here.

def index(request):
    dict = {'name': "pratham" , 'num' : 500}
    return render(request , 'app1/index.html' , context=dict)

@login_required
def special(request):
    return HttpResponse("You are logged in , Nice")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def relative(request):
    return render(request , 'app1/relative.html')



def other(request):
    return render(request , 'app1/other.html')




def users(request):
    registered = False




    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)


        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors , profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()


    return render(request , 'app1/models.html' , {'user_form':user_form , 'profile_form': profile_form , 'registered':registered})



def user_login(request):
    tries = 0

    if request.method == "POST":
        tries += 1
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username = username , password = password)

        if user:
            if user.is_active:
                login(request , user)
                return render(request , 'app1/login.html' , {'username':username})

            else:
                return HttpResponse("Account Not active")

        else:
            print("Someone tried to login and failed!!")
            return render(request, 'app1/login.html' , {'statement':"Invalid Credentials" , 'tries': tries})

    else:
        return render(request , 'app1/login.html' , {'tries': tries})

Models/project/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static "css/base3.css" %}">
</head>


<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'app1:other' %}">About Us</a>
        </li>

          <li class="nav-item">
          <a class="nav-link" href="{% url 'app1:relative' %}">Top Songs</a>
        </li>

        {% if user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>

        {% endif  %}

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block body_block%}
{% endblock %}



</body>
</html>

Models/project/templates/app1/index.html
{% extends 'app1/base.html' %}

{% load static %}
{% block body_block %}

<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
     <link rel="stylesheet" href="{% static "css/base3.css" %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/jumbotron/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>

<main>
  <div class="container py-4">


    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Canción</h1>
        <p class="col-md-8 fs-4">Hey!! , Welcome To Our Website Cancion. Here you can a stream high quality music without any ads. Check Out Top chart songs below
        mauris ultrices eros in cursus turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo</p>
        <button class="btn btn-primary btn-lg" type="button"><a href="{% url 'app1:relative' %}">TOP SONGS</a></button>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Create Account</h2>

          <p>To enjoy nonstop stream of hit songs create a account for free
          mauris ultrices eros in cursus turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo</p>
          <button class="btn btn-outline-light" type="button"><a href="{% url 'app1:users'%}">SIGN UP</a></button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Aldready A User?</h2>

          <p>mauris ultrices eros in cursus turpis massa tincidunt dui ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo</p>
          <button class="btn btn-primary" type="button"><a href="{% url 'app1:user_login' %}">LOGIN</a></button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2021
    </footer>
  </div>
</main>
{% endblock %}

Models/project/templates/app1/login.html
<!DOCTYPE html>
{% extends 'app1/base.html' %}

{% block body_block %}


{% if user.is_authenticated %}

<h1>Welcome,</h1>
<br>
<h1>{{username|upper}}</h1>
<h2>Thanks for Creating A account on Cancion, Our services will start soon!</h2>

{% else %}

{% if tries %}
<p class = "sign">Invalid Credentials Try Again</p>

{% else %}
<p class = "sign">Please Login</p>


{% endif %}
<form class = "login-form" action="{% url 'app1:user_login' %}" method = "POST">

    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name = "username" placeholder = "Enter Username">
    <br>
    <br>
    <label for="password">Password:</label>
    <input type="password" name = "password" placeholder = "Enter Password">
    <br>
    <br>

    <input type="submit" value = "Login" class = "btn btn-danger">

</form>

{% endif %}

{% endblock %}

Models/project/templates/app1/models.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends 'app1/base.html' %}

{% block body_block %}


<div class = "container">
    {% if registered %}
    <h1>Thank you for registering</h1>

    {% else %}

    <p class = "sign">SIGN UP HERE!</p>
    <div class = "form container">
        <form method = "POST" enctype = "multipart/form-data">
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% csrf_token %}
        <input type="submit" value = "Submit" class = "btn btn-danger">

    </form>
    </div>


    {% endif %}

</div>



{% endblock %}

Models/project/templates/app1/other.html
<!DOCTYPE html>
{% extends 'app1/base.html' %}
{% load static %}
{% block body_block %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">


    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/carousel/">



    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>


<main>




  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
  <br>
  <br>
  <br>

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">

           <img src="{% static "images/pic.jpg" %}" width="140" height="140">




        <h2>PRATHAM</h2>
        <p>Dynamic , radiant , and courageous - He is a star ans he knows it</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="{% static "images/pic2.jpg" %}" width="140" height="140">
        <h2>SAMIKSHA</h2>
        <p>Samiksha cares about the minor details, and they are proud to be a good friend and family member who always comes through when it counts , and who cheers people up when they are feeling down</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
         <img src="{% static "images/pic3.jpg" %}" width="140" height="140">
        <h2>SAMRUDDHI</h2>
        <p>A born adventurer, Samruddhi has boundless faith and a postive attitude, which guides them through life.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>






{% endblock %}